#!/usr/bin/env bun
import { runRecon } from "./recon";
import { PoliteScraper, type ExtractorConfig } from "./scrape";
import { Database } from "bun:sqlite";
import * as readline from "readline";

const SERVER_NAME = "site-to-sqlite-mcp";
const SERVER_VERSION = "1.0.0";
const PROTOCOL_VERSION = "2024-11-05";

const TOOLS = [
  {
    name: "site_recon",
    description:
      "Performs deep website reconnaissance without heavy token usage. Probes robots.txt, sitemaps (including .xml.gz), RSS/Atom feeds, Next.js __NEXT_DATA__ / Nuxt hydration state, and Schema.org JSON-LD structured data.",
    inputSchema: {
      type: "object",
      properties: {
        url: { type: "string", description: "Target website URL (e.g. https://example.com)" },
        limit: { type: "number", description: "Max sitemap URLs to collect (default: 500)" },
      },
      required: ["url"],
    },
  },
  {
    name: "site_scrape",
    description:
      "Executes a high-speed, polite web scrape into a local SQLite database using Bun, dynamic column evolution, rate-limiting jitter, and checkpoint/resume.",
    inputSchema: {
      type: "object",
      properties: {
        config: {
          type: "object",
          description:
            "Extraction configuration JSON (specifying tableName, startUrls, itemSelector, fields, pagination, and options).",
        },
        dbPath: {
          type: "string",
          description: "Target SQLite database file path (e.g. data.sqlite or /path/to/db.sqlite)",
        },
      },
      required: ["config"],
    },
  },
  {
    name: "site_inspect_db",
    description:
      "Inspects an SQLite database generated by site-to-sqlite. Returns table names, schemas, total row counts, sample data, executes custom SQL queries, or exports tables to CSV/JSON.",
    inputSchema: {
      type: "object",
      properties: {
        dbPath: { type: "string", description: "Path to SQLite database file" },
        table: { type: "string", description: "Optional specific table to inspect or export" },
        limit: { type: "number", description: "Number of sample rows to preview (default: 5)" },
        query: { type: "string", description: "Optional SQL SELECT query to execute" },
        exportCsv: { type: "string", description: "Optional file path to export table as CSV" },
        exportJson: { type: "string", description: "Optional file path to export table as JSON" },
      },
      required: ["dbPath"],
    },
  },
];

async function handleToolCall(name: string, args: any): Promise<any> {
  if (name === "site_recon") {
    const report = await runRecon({
      url: args.url,
      limit: args.limit || 500,
    });
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(report, null, 2),
        },
      ],
    };
  }

  if (name === "site_scrape") {
    const dbPath = args.dbPath || "data.sqlite";
    const config: ExtractorConfig = args.config;
    const scraper = new PoliteScraper(dbPath, config);
    const stats = await scraper.run();
    scraper.close();

    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            {
              message: "Scraping completed successfully",
              dbPath,
              tableName: config.tableName,
              stats,
            },
            null,
            2
          ),
        },
      ],
    };
  }

  if (name === "site_inspect_db") {
    const dbPath = args.dbPath;
    const file = Bun.file(dbPath);
    if (!(await file.exists())) {
      return {
        isError: true,
        content: [{ type: "text", text: `Database file not found: ${dbPath}` }],
      };
    }

    const db = new Database(dbPath);
    try {
      if (args.query) {
        const rows = db.prepare(args.query).all();
        return {
          content: [
            {
              type: "text",
              text: JSON.stringify({ query: args.query, totalRows: rows.length, rows }, null, 2),
            },
          ],
        };
      }

      const tables = db
        .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';")
        .all() as { name: string }[];

      const summary: Record<string, any> = {};

      for (const { name: tblName } of tables) {
        const countRow = db.prepare(`SELECT COUNT(*) as count FROM "${tblName}";`).get() as { count: number };
        const cols = db.prepare(`PRAGMA table_info("${tblName}");`).all() as { name: string; type: string }[];
        const sampleLimit = args.limit ?? 5;
        const samples = sampleLimit > 0 ? db.prepare(`SELECT * FROM "${tblName}" LIMIT ?;`).all(sampleLimit) : [];

        summary[tblName] = {
          totalRows: countRow.count,
          columns: cols.map((c) => `${c.name} (${c.type})`),
          samples,
        };

        if (args.exportJson && (args.table === tblName || (!args.table && tblName !== "crawled_urls"))) {
          const allRows = db.prepare(`SELECT * FROM "${tblName}";`).all();
          await Bun.write(args.exportJson, JSON.stringify(allRows, null, 2));
          summary[tblName].exportedJson = args.exportJson;
        }

        if (args.exportCsv && (args.table === tblName || (!args.table && tblName !== "crawled_urls"))) {
          const allRows = db.prepare(`SELECT * FROM "${tblName}";`).all() as Record<string, any>[];
          if (allRows.length > 0) {
            const headers = Object.keys(allRows[0]);
            const csvRows = [headers.join(",")];
            for (const r of allRows) {
              const vals = headers.map((h) => {
                const v = r[h];
                if (v === null || v === undefined) return '""';
                return `"${String(v).replace(/"/g, '""')}"`;
              });
              csvRows.push(vals.join(","));
            }
            await Bun.write(args.exportCsv, csvRows.join("\n"));
            summary[tblName].exportedCsv = args.exportCsv;
          }
        }
      }

      return {
        content: [
          {
            type: "text",
            text: JSON.stringify({ dbPath, tables: summary }, null, 2),
          },
        ],
      };
    } finally {
      db.close();
    }
  }

  throw new Error(`Unknown tool: ${name}`);
}

function sendResponse(id: any, result: any) {
  const msg = JSON.stringify({ jsonrpc: "2.0", id, result });
  process.stdout.write(msg + "\n");
}

function sendError(id: any, code: number, message: string) {
  const msg = JSON.stringify({ jsonrpc: "2.0", id, error: { code, message } });
  process.stdout.write(msg + "\n");
}

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: false,
});

rl.on("line", async (line) => {
  const trimmed = line.trim();
  if (!trimmed) return;

  try {
    const message = JSON.parse(trimmed);
    const { id, method, params } = message;

    if (method === "initialize") {
      sendResponse(id, {
        protocolVersion: PROTOCOL_VERSION,
        capabilities: {
          tools: {},
        },
        serverInfo: {
          name: SERVER_NAME,
          version: SERVER_VERSION,
        },
      });
      return;
    }

    if (method === "notifications/initialized") {
      // No response needed for notifications
      return;
    }

    if (method === "ping") {
      sendResponse(id, {});
      return;
    }

    if (method === "tools/list") {
      sendResponse(id, { tools: TOOLS });
      return;
    }

    if (method === "tools/call") {
      const toolName = params?.name;
      const toolArgs = params?.arguments || {};
      try {
        const res = await handleToolCall(toolName, toolArgs);
        sendResponse(id, res);
      } catch (err: any) {
        sendResponse(id, {
          isError: true,
          content: [{ type: "text", text: `Tool error (${toolName}): ${err.message || String(err)}` }],
        });
      }
      return;
    }

    if (id !== undefined) {
      sendError(id, -32601, `Method not found: ${method}`);
    }
  } catch (err: any) {
    if (line.includes('"id":')) {
      sendError(null, -32700, `Parse error: ${err.message}`);
    }
  }
});
